### ISSUE TITLE
python34 and gnuplot5 error during import

### ISSUE THREAD

**Issue by autosquid** [dkogan/gnuplotlib#1]
>>>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uuplusu/anaconda/envs/py34/lib/python3.4/site-packages/gnuplotlib.py", line 704, in <module>
    features = _getGnuplotFeatures()
  File "/Users/uuplusu/anaconda/envs/py34/lib/python3.4/site-packages/gnuplotlib.py", line 688, in _getGnuplotFeatures
    features = set( re.findall(r'--([a-zA-Z0-9_]+)', helpstring) )
  File "/Users/uuplusu/anaconda/envs/py34/lib/python3.4/re.py", line 210, in findall
    return _compile(pattern, flags).findall(string)
TypeError: can't use a string pattern on a bytes-like object

**Comment by dkogan** [comment]
Hi. Python3 is not supported. If you give me reasonable patches, I'll be happy to add that support.

**Comment by autosquid** [comment]
with  `gnuplot -h` I got:
>>>
Usage: gnuplot [OPTION] ... [FILE]
for X11 options see 'help X11->command-line-options'
  -V, --version
  -h, --help
  -p  --persist
  -d  --default-settings
  -c  scriptfile ARG1 ARG2 ...
  -e  "command1; command2; ..."

**Comment by autosquid** [comment]
yes, this this related with python3 string. the helpsstring of bytes class, but re. need string.
