### ISSUE TITLE
OSError: [WinError 10093] Either the application has not called WSAStartup, or WSAStartup failed

### ISSUE THREAD

**Issue by ReinaFeng** [dkogan/gnuplotlib#16]
Hi,

when I run on windows. It shows:

>>> gp.plot( np.linspace(-5,5,30)**2,unset='grid', terminal='dumb 80 40' )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rounan_feng\AppData\Local\Programs\Python\Python38\lib\site-packages\gnuplotlib.py", line 2648, in plot
    globalplot = gnuplotlib(**jointOptions)
  File "C:\Users\rounan_feng\AppData\Local\Programs\Python\Python38\lib\site-packages\gnuplotlib.py", line 1480, in __init__
    self._startgnuplot()
  File "C:\Users\rounan_feng\AppData\Local\Programs\Python\Python38\lib\site-packages\gnuplotlib.py", line 1534, in _startgnuplot
    errorMessage, warnings = self._checkpoint('printwarnings')
  File "C:\Users\rounan_feng\AppData\Local\Programs\Python\Python38\lib\site-packages\gnuplotlib.py", line 1694, in _checkpoint
    rlist,wlist,xlist = select.select([self.gnuplotProcess.stderr],[], [],
OSError: [WinError 10093] Either the application has not called WSAStartup, or WSAStartup failed

Is that possible to solve?

**Comment by dkogan** [comment]
Hi. I don't use windows, so I can't help you. I'm sure making it work there is possible, but somebody else would have to actually implement it, and to do the work. Something's wrong with select(), but I don't know what.

Other reports that you may find helpful:

https://github.com/dkogan/gnuplotlib/pull/15

https://github.com/dkogan/gnuplotlib/issues/6

Patches welcome

**Comment by dkogan** [comment]
Closing old report. If somebody wants to work on it, please get in touch with me.
