### ISSUE TITLE
 AttributeError: 'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by warriorjacq9** [dkogan/gnuplotlib#26]
After trying to make a plot with this code:
```python
plt.plot((_x, _i, {'legend': 'incandescent'}),
         (_x, _c, {'legend': 'CFC'}),
         (_x, _h, {'legend': 'Halogen'}),
         (_x, _l, {'legend': 'LED'}),
         _with='lines',
         terminal='dumb 120,40')
```
I get this error:
```python

Traceback (most recent call last):
  File "index.py", line 47, in <module>
    terminal='dumb 120,40')
  File "/usr/local/lib/python3.7/site-packages/gnuplotlib.py", line 2669, in plot
    globalplot.plot(*curves)
  File "/usr/local/lib/python3.7/site-packages/gnuplotlib.py", line 2501, in plot
    *curves, **jointOptions), )
  File "/usr/local/lib/python3.7/site-packages/gnuplotlib.py", line 2486, in make_subplot_data
    subplotOptions)
  File "/usr/local/lib/python3.7/site-packages/gnuplotlib.py", line 2122, in _massageAndValidateArgs
    curves = [ reformat(curve) for curve in curves ]
  File "/usr/local/lib/python3.7/site-packages/gnuplotlib.py", line 2122, in <listcomp>
    curves = [ reformat(curve) for curve in curves ]
  File "/usr/local/lib/python3.7/site-packages/gnuplotlib.py", line 2105, in reformat
    if all( x.size <= 0 for x in curve ):
  File "/usr/local/lib/python3.7/site-packages/gnuplotlib.py", line 2105, in <genexpr>
    if all( x.size <= 0 for x in curve ):
AttributeError: 'list' object has no attribute 'size'
```
Expected output is a graph showing all four lines across x.

**Comment by dkogan** [comment]
All your data arguments should be numpy arrays. I bet some of them are plain Python lists. Yes?

**Comment by warriorjacq9** [comment]
Thanks so much! I was using plain lists. After modifying it to use numpy lists it worked properly.
