### ISSUE TITLE
Gnuplot process no longer responding

### ISSUE THREAD

**Issue by autosquid** [dkogan/gnuplotlib#3]
With the first example (x^2), under python3/gunplot5.
Aftering fixing the string problem (RP. https://github.com/dkogan/gnuplotlib/pull/2) , I met this. I thought maybe there's some advice from you for me to make another fix.

>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uuplusu/anaconda/envs/py34/lib/python3.4/site-packages/gnuplotlib.py", line 1607, in plot
    globalplot = gnuplotlib(**plotOptions)
  File "/Users/uuplusu/anaconda/envs/py34/lib/python3.4/site-packages/gnuplotlib.py", line 760, in __init__
    self._startgnuplot()
  File "/Users/uuplusu/anaconda/envs/py34/lib/python3.4/site-packages/gnuplotlib.py", line 782, in _startgnuplot
    self._safelyWriteToPipe("set terminal push", 'terminal')
  File "/Users/uuplusu/anaconda/envs/py34/lib/python3.4/site-packages/gnuplotlib.py", line 1008, in _safelyWriteToPipe
    errorMessage, warnings = self._checkpoint('printwarnings')
  File "/Users/uuplusu/anaconda/envs/py34/lib/python3.4/site-packages/gnuplotlib.py", line 1105, in _checkpoint
    and/or gnuplot itself. Please report this as a gnuplotlib bug''')
gnuplotlib.GnuplotlibError: Gnuplot process no longer responding. This is likely a bug in gnuplotlib
and/or gnuplot itself. Please report this as a gnuplotlib bug

**Comment by dkogan** [comment]
Use a syscall tracer (strace, sysdig, etc) to see exactly what is being read/written internally. That'll tell you where the issue lies.

**Comment by dkogan** [comment]
Closing. Need more specific information.
